[build-system]
requires = ["setuptools", "wheel", "cffi", "pep517", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "deciphon_api"
authors = [{ name = "Danilo Horta", email = "danilo.horta@pm.me" }]
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.8"
dependencies = ["typer"]

[project.urls]
Home = "http://github.com/EBI-Metagenomics/deciphon-cli"
